### ISSUE TITLE
Change "Path to core-Versioninfo" in admin.php

### ISSUE THREAD

**Issue by lck-git** [TN03/hi_updatecheck#3]
https://github.com/TN03/hi_updatecheck/blob/master/admin.php#L39
New:
http://www.cmsimple-xh.org/userfiles/downloads/versioninfo/cmsimple_xh-version.nfo

More Info at [CMSimple_XH-Forum](https://cmsimpleforum.com/viewtopic.php?f=16&t=12729&p=60277#p60277).

**Comment by TN03** [comment]
@lck-git 
Thanks for reporting.

**Comment by cmb69** [comment]
IMO, this would be particularly useful to support multiple major versions (well, in our case actually minor versions). On the server, for example, `version-1.6,nfo` would hold the version info for XH 1.6, and `version-1.7.nfo` would hold the info for XH 1.7. As soon as XH 1.6 has its end-of-life, `version-1.6.nfo` would hold the version info of XH 1.7. It's actually too late for XH 1.6/1.7 to be useful, but may be in the future.
